image: node:4.2.2

cache:
  paths: 
    - node_modules/ # Node modules and dependencies

before_script:
  - npm install gitbook-cli -g
  - gitbook fetch latest 

pages:
  stage: deploy
  script:
    - gitbook build
  artifacts:
    paths:
      - public 
